### ISSUE TITLE
Concurrencia CPU

### ISSUE THREAD

**Issue by tferraro** [sisoputnfrba/2015-2c-cache13-enunciado#2]
Buenas,

Hago una pregunta (_más que nada es un assertion_) sobre algo que creo que el enunciado deja medio ambiguo..o es apropósito.
**Los hilos de CPU se conectan de manera independiente al server multihilo del administrador de memoria?**

**Comment by fran-bravo** [comment]
Buena deteccion tom 
En realidad los dejamos elegir la implementacion que prefieran, se hablo en esta [discusion](https://groups.google.com/forum/m/?hl=es#!topic/so-ayudantes/tQoIvaYyHPE). 
Asi que si, queda un tanto ambiguo decirles **server multihilo**

**Comment by tferraro** [comment]
Peefectirigillo. Me habia olvidado de esa discusión ;P
